services:
  postgres:
    image: postgres:17
    container_name: postgres
    hostname: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 12s
      timeout: 6s
      retries: 3
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kong}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      POSTGRES_USER: ${POSTGRES_USER:-kong}
    ports:
      - "5432:5432"
  