# https://ruanbekker.medium.com/ship-your-docker-logs-to-loki-using-fluentbit-dd95fe69fb33
[SERVICE]
    Flush           5
    Daemon          Off
    Log_Level       Info
    Parsers_File    parsers.conf
    HTTP_Server     Off

[INPUT]
    Name            tcp
    Listen          0.0.0.0
    Port            5171
    Chunk_Size      32
    Buffer_Size     64
    Format          json
    Tag             kong-internal


[INPUT]
    Name            tcp
    Listen          0.0.0.0
    Port            5170
    Chunk_Size      32
    Buffer_Size     64
    Format          json
    Tag             kong-external


[INPUT]
    Name            tcp
    Listen          0.0.0.0
    Port            5172
    Chunk_Size      32
    Buffer_Size     64
    Format          json
    Tag             kong-manager

[OUTPUT]
    Name                loki
    Match               kong-internal
    Labels              job=kong-internal
    Host                loki
    Port                3100


[OUTPUT]
    Name                loki
    Match               kong-external
    Labels              job=kong-external
    Host                loki
    Port                3100


[OUTPUT]
    Name                loki
    Match               kong-manager
    Labels              job=kong-manager
    Host                loki
    Port                3100

